namespace CParser
{
    public enum CTokenType
    {
        IDENTIFIER, CONSTANT, STRING_LITERAL, SIZEOF,
        PTR_OP, INC_OP, DEC_OP, LEFT_OP, RIGHT_OP, LE_OP, GE_OP, EQ_OP, NE_OP,
        AND_OP, OR_OP, MUL_ASSIGN, DIV_ASSIGN, MOD_ASSIGN, ADD_ASSIGN,
        SUB_ASSIGN, LEFT_ASSIGN, RIGHT_ASSIGN, AND_ASSIGN,
        XOR_ASSIGN, OR_ASSIGN, TYPE_NAME,

        TYPEDEF, EXTERN, STATIC, AUTO, REGISTER,
        CHAR, SHORT, INT, LONG, SIGNED, UNSIGNED, FLOAT, DOUBLE, CONST, VOLATILE, VOID,
        STRUCT, UNION, ENUM, ELLIPSIS,

        CASE, DEFAULT, IF, ELSE, SWITCH, WHILE, DO, FOR, GOTO, CONTINUE, BREAK, RETURN,

        SEMICOLON, LEFT_BRACE, RIGHT_BRACE, COMMA, COLON, 
        ASSIGN_OP, LEFT_PAREN, RIGHT_PAREN, LEFT_BRACKET, RIGHT_BRACKET, 
        INST_OP, BIT_AND_OP, NOT_OP, BIT_NOT_OP, SUB_OP, ADD_OP, MUL_OP, DIV_OP, MOD_OP, 
        LT_OP, GT_OP, XOR_OP, BIT_OR_OP, QUERY,

        COMMENT,

        EOF
    }
}
